{
    'name': 'Sample Request',
    'version': '19.0.1.0.0',
    'summary': 'Manage free sample request with approval workflow',
    'depends': ['sale', 'stock', 'mail', 'Yohannes_sales_credit_cash'],
    'author': '',
    'license': 'AGPL-3',
    'data': [
        'security/sample_request_security.xml',
        'security/ir.model.access.csv',
        'data/free_sample_request_data.xml',
        'data/return_sample_request_data.xml',
        'data/issues_request_data.xml',
        'data/issues_recives_data.xml',
        'data/return_sample_data.xml',
        'data/consignment_picking_sequence.xml',
        'data/request_dashboard_data.xml',
        'views/request_dashboard_views.xml',
        'views/free_sample_request_views.xml',
        'views/reternd_sample_request_views.xml',
        'views/sample_return_views.xml',
        'views/sample_request_action_views.xml',
        'views/sample_request_menu_views.xml',
        'views/stock_location_views.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_extension_views.xml',
    ],
    'installable': True,
    'application': False,
}
