{
    'name': 'Sales approval Workflows',
    'version': '19.0.1.0.3',
    'category': 'Sales',
    'summary': 'multi level approval manegement',
    'author': 'eden',
    'license': 'AGPL-3',
    'depends': ['sale', 'sale_stock', 'crm', 'stock', 'account', 'mail', 'inventory', 'product_expiry', 'purchase', 'Yohannes_sales_credit_cash', 'Yohannes_sales_person_target_management'],

    'data': [
        'security/sale_approval_security.xml',
        'security/ir.model.access.csv',
        'data/auto_cancel_cron.xml',
        'views/res_config_settings_views.xml',
        'views/stock_location_views.xml',
        'views/stock_picking_views.xml',
        'views/sale_order_views.xml',
        'views/account_journal_views.xml',
        'wizard/products_lots_report_wizard_views.xml',
        'report/products_lots_report.xml',
        'views/account_menus.xml',
        'views/account_move_views.xml',
        'views/matured_customers_views.xml',
        'views/product_views.xml',
        'views/res_partner_views.xml',
        'views/stock_quant_views.xml',
    ],
    'installable': True,
    'application': False,
}
