from . import daily_sales
from . import monthly_sales
from . import weekly_sales
from . import sale_order
from . import res_users
from . import account_move
from . import inventory_date_change
from . import invoice_extension
from . import sales_target_config
from . import crm_team
from . import stock_move
