{
    'name': 'Yohannes sales peron Targate management Sale Order',
    'version': '1.0',
    'summary': 'Add Batch Number and Expiration Date to Sales Order Lines',
    'description': 'Extends sales order lines to include batch number and expiration date in tree view.',
    'category': 'Sales',
    'depends': ['base', 'crm', 'sale', 'purchase', 'stock', 'sales_team', 'mail', 'sale_stock', 'yohannes_account_withholding_tax'],
    'data': [

        'security/sale_targate_security.xml',
        'security/ir.model.access.csv',
        'data/sales_targate_seq.xml',
        'views/res_users_views.xml',
        'views/sales_target_config_views.xml',
        'views/sale_order_views.xml',
        'views/daily_sales_views.xml',
        'views/monthly_sales_views.xml',
        'views/account_invoice_custom.xml',
        'views/weekly_sales_views.xml',
        'views/sales_targate_acctions_views.xml',
        'views/sales_targate_menu_views.xml',
        'views/transaction_type_views.xml',
        'views/withholding_followup_views.xml',
        'views/stock_valuation_views.xml',
        'views/crm_team_views.xml',
        'views/payment_followup_views.xml',
        'report/daily_sales_report.xml',
        'report/report_daily_sales.xml',
        'report/monthly_sales_report.xml',
        'report/report_monthly_sales.xml',
        'report/weekly_sales_report.xml',
        'report/report_weekly_sales.xml',
        'report/invoice_report.xml',
        'report/withholding_report.xml',
        'report/withholding_report_templates.xml',
        'report/report_crv.xml',
        # 'report/sales_report.xml',

    ],
    'installable': True,
    'application': False,
}
