from odoo import _, fields, models, api
from dateutil.relativedelta import relativedelta
from odoo.exceptions import ValidationError
from odoo.exceptions import UserError

# WARNING: DO NOT EDIT THIS FILE MANUALLY WHILE THE AGENT IS WORKING. 
# YOUR IDE AUTO-SAVE IS REVERTING FIXES. PLEASE CLOSE THIS FILE AND RESTART ODOO.

import logging

_logger = logging.getLogger(__name__)

class SaleDiscountWizard(models.TransientModel):
    _name = 'sale.discount.wizard'
    _description = 'Sale Discount wizard'

    order_id = fields.Many2one('sale.order', required=True)
    line_ids = fields.One2many('sale.discount.wizard.line', 'wizard_id', string='Discount Rules')

    def validate(self):
        self.ensure_one()
        order = self.order_id
        line_dict = {}  # line_id -> {'add': float, 'rules': [str]}

        for wline in self.line_ids.filtered('apply'):
            for aline_id in wline.applicable_line_ids.ids:
                if aline_id not in line_dict:
                    line_dict[aline_id] = {'add': 0.0, 'rules': []}
                # Sum the percentages
                line_dict[aline_id]['add'] += wline.percentage
                if wline.reference and wline.reference not in line_dict[aline_id]['rules']:
                    line_dict[aline_id]['rules'].append(wline.reference)

        for line_id, data in line_dict.items():
            line = order.order_line.browse(line_id)
            if data['rules']:
                line.write({
                    'discount': data['add'],
                    'discount_rule_display': ', '.join(data['rules'])
                })

        # Trigger approval if context is set
        approval_context = self._context.get('approval_context')
        if approval_context == 'submit':
            return order.with_context(approval_from_wizard=True).action_submit_for_approval()
        elif approval_context == 'approve_price':
            return order.with_context(approval_from_wizard=True).action_approve_price_change()

        # Odoo 17/19 requires act_window_close with underscores
        return {'type': 'ir.actions.act_window_close'}

class SaleDiscountWizardLine(models.TransientModel):
    _name = 'sale.discount.wizard.line'
    _description = 'Sale Discount wizard Line'

    wizard_id = fields.Many2one('sale.discount.wizard', required=True)
    rule_model = fields.Char(string='Rule Model')
    rule_id = fields.Integer(string='Rule ID')
    reference = fields.Char(string='Rule Reference')
    percentage = fields.Float(string='Percentage')
    apply = fields.Boolean(string='Apply', default=True)
    applicable_line_ids = fields.Many2many('sale.order.line', string='Applicable Lines')
    reason = fields.Char(compute='_compute_reason', string='Applies Because')

    @api.depends('rule_model', 'rule_id', 'percentage')
    def _compute_reason(self):
        for line in self:
            if line.rule_model == 'discount.per.sales.amount':
                line.reason = f"Sales amount in range → {line.percentage:+.2f}%"
            elif line.rule_model == 'discount.per.customer.type':
                line.reason = f"Customer type + category/core → {line.percentage:+.2f}%"
            elif line.rule_model == 'discount.per.quantity.order':
                line.reason = f"Quantity in range → {line.percentage:+.2f}%"
            elif line.rule_model == 'discount.per.customer.and.product':
                line.reason = f"Specific customer + product → {line.percentage:+.2f}%"
            else:
                line.reason = f"{line.percentage:+.2f}%"
