from . import hr_contribution_register
from . import hr_salary_rule_category
from . import hr_salary_rule
from . import hr_payroll_structure
from . import hr_payroll_structure_type
from . import hr_payslip_input
from . import hr_payslip_worked_days
from . import hr_payslip_line
from . import hr_payslip
from . import hr_payslip_run
from . import hr_version
from . import payroll_leftovers
